### ISSUE TITLE
Issue reading xml

### ISSUE THREAD

**Issue by jumbojoffer** [Karlovsky120/7DaysProfileEditor#42]
-----------------------------------------------------
Log started at: 01.05.2019 21:59:37
-----------------------------------------------------

Time Stamp: 01.05.2019 21:59:41
Message: Length cannot be less than zero.
Parameter name: length
Source: mscorlib
Exception: System.ArgumentOutOfRangeException: Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at SevenDaysProfileEditor.Data.XmlData.GetItems()
   at SevenDaysProfileEditor.Program.Initialize()
Target Site: System.String Substring(Int32, Int32)

Selected 7daystodie.exe as instructed by the program, was left with error message. Log entry above.

**Comment by Karlovsky120** [comment]
Editor does not work with the latest version of the game (A17), nor is it still maintained.

**Comment by jumbojoffer** [comment]
I tried with alpha 16.4 release.

**Comment by Karlovsky120** [comment]
As I said, the program is no longer mantained.

**Comment by jumbojoffer** [comment]
Sucks, but oh well. Thanks for the help.

**Comment by Karlovsky120** [comment]
Sorry. It is open source though, so anyone is free to take up the development of the program if they so desire.
